name: CraftJS CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 16
      - name: Build CraftJS
        run: |
          npm install --prefix=core
          npm install --prefix=internal
          ./build.sh
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: craftjs.jar
          path: java/target/craftjs.jar
  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '22.3.1'
          java: java17
          arch: amd64
      - uses: actions/download-artifact@v2
        with:
          name: craftjs.jar
      - name: Install JS support
        run: gu install js
      - name: Setup server
        run: |
          mkdir plugins
          mv craftjs.jar plugins
          wget -c https://papermc.io/api/v2/projects/paper/versions/1.19.3/builds/384/downloads/paper-1.19.3-384.jar -O paper.jar
      - name: Run tests
        run: |
          java -Dcom.mojang.eula.agree=true -Dcraftjs.runTests=craftjs-internal -jar paper.jar
